### ISSUE TITLE
(enhancement) Adding additional architectures

### ISSUE THREAD

**Issue by GoliathLabs** [roundcube/roundcubemail-docker#173] opened 2022-02-08 16:41 UTC
### Is your feature request related to a problem? Please describe.
I wanted to try this roundcube image on my ARM64 cloud instance. Currently, however, I can only do this by rebuilding the image on the instance each time.

---
### Describe the solution you'd like
It is relatively easy to extend the GitHub actions to build images for other architectures (e.g. arm/v5, arm/v7, arm64/v8, ppc64le, etc). This way, users on other architectures can also use the Docker image for Roundcube.

---
### Describe alternatives you've considered
Not supporting the architecture at all. However, there are now more and more users on other architectures (e.g. ARM64 on the Rapsberry Pi or Ampere A1 cloud instances on Oracle).

---
### Additional context
I have already added the additional architectures to some projects I work with frequently (see: https://github.com/freifunkMUC/wg-access-server/blob/master/.github/workflows/docker.yml). The PHP Docker images support a large number of architectures. You might want to add some others if ARM64 should be added to the workflow.

**Comment by thomascube** [comment] 2022-02-08 21:05
Duplicate of #122. We're open for help and contributions on this topic. @williamdes has already done some work. Please follow-up in issue #122.

**Closed by thomascube** 2022-02-08 21:05 UTC
