### ISSUE TITLE
Login Failed when Roundcube is in a sub path.

### ISSUE THREAD

**Issue by ricariel** [roundcube/roundcubemail-docker#186] opened 2022-07-29 08:20 UTC
When installing behind reverse proxy (traefik) login redirects to / instead of defined sub path. Form shows / as target not ./

    labels:
      - traefik.enable=true
      - traefik.http.routers.roundcube.rule=Host(`www.example.com`,`example.com`) && ( PathPrefix(`/mail`) || PathPrefix(`/webmail`))
      - traefik.http.routers.roundcube.entrypoints=websecure
      - traefik.http.routers.roundcube.tls=true
      - traefik.http.middlewares.roundcube-proxy.stripprefix.prefixes=/webmail,/mail
      - traefik.http.routers.roundcube.middlewares=roundcube-proxy

**Comment by ricariel** [comment] 2022-07-29 08:21
Just happened with 1.6 label. With 1.5.3 it works.

**Comment by ghnp5** [comment] 2022-08-10 22:33
Same. Log-in is redirecting to `/?_task=login` instead of `/subpath/?_task=login`.

**Comment by logopk** [comment] 2022-08-11 04:56
Old behavior was `./?_task=login`

**Comment by s0ftcorn** [comment] 2022-09-15 12:01
Im experiencing the same on multiple systems. 1.5.3 works as expected while 1.6.0 is having the issue.

In https://github.com/roundcube/roundcubemail-docker/commit/0296150d297aa055dd699d8743f5606d6826babc there is really just a config change:

from:
```
 \$config['default_host'] = '${ROUNDCUBEMAIL_DEFAULT_HOST}';
  \$config['default_port'] = '${ROUNDCUBEMAIL_DEFAULT_PORT}';
  \$config['smtp_server'] = '${ROUNDCUBEMAIL_SMTP_SERVER}';
  \$config['smtp_port'] = '${ROUNDCUBEMAIL_SMTP_PORT}';
```
  
  to:
  ```
\$config['imap_host'] = '${ROUNDCUBEMAIL_DEFAULT_HOST}:${ROUNDCUBEMAIL_DEFAULT_PORT}';
  \$config['smtp_host'] = '${ROUNDCUBEMAIL_SMTP_SERVER}:${ROUNDCUBEMAIL_SMTP_PORT}';
```
  
 So maybe this is not a problem of the dockerized version but of roundcube itself?

**Comment by ghnp5** [comment] 2022-11-23 10:24
Proposed solution: https://github.com/roundcube/roundcubemail/pull/8770

**Comment by ghnp5** [comment] 2023-01-20 19:37
Hey. Any update on when will this be released to the Docker version? I'm using the latest version of Roundcube and this is still broken. I haven't been able to use Roundcube at all since this has been broken. Thank you very much!

**Comment by bubeck** [comment] 2023-02-05 20:46
It seems to be released as 1.6.1 However, the problem is still there.

**Comment by s0ftcorn** [comment] 2023-02-05 21:00
> It seems to be released as 1.6.1 However, the problem is still there.

confirmed.

**Comment by thomascube** [comment] 2023-02-07 20:43
There is a solution in 1.6.1 but it still requires some configuration on the Roundcube side and isn't yet documented.
See https://github.com/roundcube/roundcubemail/blob/master/config/defaults.inc.php#L821-L829

In short: either set the sub-path as fixed value with the config option `request_path` or configure the reverse-proxy to send the path with a custom header (e.g. X-Forwarded-Path) and set `$config['request_path'] = 'HTTP_X_FORWARDED_PATH';` to read the path from the proxy header.

**Comment by ghnp5** [comment] 2023-02-08 20:38
@thomascube - thanks. If we are using Docker, we can't change the defaults file. Is there a way to set this value alone, without having to mount the whole defaults file? Or an environment variable?

**Comment by bubeck** [comment] 2023-02-09 06:53
Confirmed! Working with this additional instructions. Thanks!

> There is a solution in 1.6.1 but it still requires some configuration on the Roundcube side and isn't yet documented. See https://github.com/roundcube/roundcubemail/blob/master/config/defaults.inc.php#L821-L829
> 
> In short: either set the sub-path as fixed value with the config option `request_path` or configure the reverse-proxy to send the path with a custom header (e.g. X-Forwarded-Path) and set `$config['request_path'] = 'HTTP_X_FORWARDED_PATH';` to read the path from the proxy header.

**Comment by s0ftcorn** [comment] 2023-02-19 19:40
How would this solution be applied to the dockerized version?

**Comment by bubeck** [comment] 2023-02-19 20:11
I use this command to run the container.

```
docker run --restart=always --name roundcubemail -p 8888:80 --volume "volume-roundcube:/var/roundcube" -e ROUNDCUBEMAIL_UPLOAD_MAX_FILESIZE=16240000 -e ROUNDCUBEMAIL_DEFAULT_HOST=tls://bubecks.de -e ROUNDCUBEMAIL_SMTP_SERVER=tls://bubecks.de -d roundcube/roundcubemail:$tag
```

The important part is the --volume that mounts to /var/roundcube, so that the volume can also contain a config directory with the needed configuration:

```
.
├── config
│   └── reverse-proxy.php
└── db
    └── sqlite.db
```

with reverse-proxy.php having the following content:

```
<?php

// Specifies the full path of the original HTTP request, either as a real path or
// $_SERVER field name. This might be useful when Roundcube runs behind a reverse
// proxy using a subpath. This is a path part of the URL, not the full URL!
// The reverse proxy config can specify a custom header (e.g. X-Forwarded-Path) containing
// the path under which Roundcube is exposed to the outside world (e.g. /rcube/).
// This header value is then available in PHP with $_SERVER['HTTP_X_FORWARDED_PATH'].
// By default the path comes from  'REDIRECT_SCRIPT_URL', 'SCRIPT_NAME' or 'REQUEST_URI',
// whichever is set (in this order).
$config['request_path'] = "/rc/";

?>
```

In my case "/rc/" is the subpath. Change as wanted.

**Comment by hasturo** [comment] 2023-04-16 14:45
If i try this in Version 1.6.1 with docker ive got a permission denied when i try to use it.  How did you copy the "application" in Roundcube Container to subfolder Location during startup?

**Comment by bubeck** [comment] 2023-04-17 07:16
I dont copy anthing. Instead I run a container with RC and configured apache running in front of it with a reverse-proxy function pointing to the docker container. This is the reverse proxy conifguration inside my apache

````
ProxyPass /rc/   http://localhost:8888/
ProxyPassReverse /rc/   http://localhost:8888/
````

**Closed** 2024-02-16 11:22 UTC

**Comment by CodeShellDev** [comment] 2025-05-25 08:11
Hello, _sorry for re-opening this_, but it seems like setting 

> `ROUNDCUBEMAIL_REQUEST_PATH=/rc`
doesn't work aynmore I am also using traefik which hosts the service at /rc.
Inspecting the container I see that the env var is correctly set, even set it in my custom config which is mounted inside of /var/rouncube/config.
Am I missing something?

I am getting a 403 Permission denied error from apache (roundcube).
Thanks in advance!

**Comment by pabzm** [comment] 2025-06-03 10:22
@CodeShellDev Please open a new issue if your problem persists, and provide more concrete details about your setup in it, so we can understand and reproduce the problem
