### ISSUE TITLE
serve under subpath

### ISSUE THREAD

**Issue by deraljoscha** [roundcube/roundcubemail-docker#180] opened 2022-06-20 18:49 UTC
So I have this roundcube docker image up and running under mydomain.com:9000
I'm using apache2 as reverse proxy and I have other apps configured as well.

now I want to serve rouncube under mydomain.com/mail
I have my apache2 config properly, but is there a variable to add so roundcube is served under a subpath?
Right now the login fails and isn't properly displayed, I can only reach rc under mydomain.com:9000

thanks in advance

**Comment by ghnp5** [comment] 2022-08-10 22:33
Same. Log-in is redirecting to `/?_task=login` instead of `/subpath/?_task=login`.
This was working before.

**Comment by logopk** [comment] 2022-08-11 04:57
Old behavior was `./?_task=login`

**Comment by bubeck** [comment] 2022-08-16 07:52
Seems to be a duplicate of https://github.com/roundcube/roundcubemail-docker/issues/186

**Closed** 2022-09-05 20:55 UTC
Labels: duplicate
