### ISSUE TITLE
Subpath no longer working

### ISSUE THREAD

**Issue by ghnp5** [roundcube/roundcubemail-docker#188] opened 2022-08-10 22:35 UTC
After upgrading Roundcube Docker to the latest version, it no longer works under a reverse proxy, under a subpath.

Log-in is redirecting to `/?_task=login` instead of `/subpath/?_task=login`.

This was working before.

**Comment by bubeck** [comment] 2022-08-16 07:51
This issue seems to be a duplicate of https://github.com/roundcube/roundcubemail-docker/issues/186

**Closed** 2022-09-01 20:53 UTC
Labels: duplicate
